### ISSUE TITLE
Clicking on some listings does not route to the proper repo

### ISSUE THREAD

**Issue by iantrich** [custom-cards/tracker-card#10]
@thomasloven in particular. Likely the 'lovelace-' prefix on his repos is through things off.

https://github.com/thomasloven/slider-entity-row

should be

https://github.com/thomasloven/lovelace-slider-entity-row

**Comment by thomasloven** [comment]
@ludeeus has some script to automatically generate the repo listing. Apparently it's not perfect yet.

**Comment by ludeeus** [comment]
This now works as intended press "Check" in the tracker-card to refresh the json values
