### ISSUE TITLE
Version numbers that use hashes to not update

### ISSUE THREAD

**Issue by iantrich** [custom-cards/tracker-card#11]
![image](https://user-images.githubusercontent.com/1287159/44436727-42338300-a57c-11e8-8023-770414c43f02.png)

I've tried to update this a few times and always reverts back to 0.0.1 with each check

**Comment by ludeeus** [comment]
The issue here are probably with the json content of the repo those are getting information from.
investigating

**Comment by ludeeus** [comment]
This should now work as expected.
