### ISSUE TITLE
RFE: color options

### ISSUE THREAD

**Issue by jmartensson** [custom-cards/tracker-card#14]
Currently there is hard do see differences of the rows
![image](https://user-images.githubusercontent.com/9382342/45239242-d9bb0480-b2e4-11e8-8de4-21d2439434fb.png)

Maybe you could add some options for coloring the rows, or add some icon just to help showing whats different. A very ugly example:
![image](https://user-images.githubusercontent.com/9382342/45239268-f5260f80-b2e4-11e8-977f-6362dd05cfc0.png)

**Comment by ludeeus** [comment]
I like it

**Comment by ludeeus** [comment]
I tried to implement this, but it will look super weird if the user has a custom theme.
