### ISSUE TITLE
custom_card/custom_component separation issue

### ISSUE THREAD

**Issue by jmartensson** [custom-cards/tracker-card#17]
Just a thing I noticed when I tried this setup in lovelace

    - type: custom:tracker-card
      title: Cards
      trackers:
        - sensor.custom_card_tracker
        
    - type: custom:tracker-card
      title: Components
      trackers:
        - sensor.custom_component_tracker

And it shows up like this:
![image](https://user-images.githubusercontent.com/9382342/45900925-7bf8e300-bde1-11e8-8ed1-359ff90862ca.png)

When clicking "check/update all" buttons on either card its checking/updating all, not the specific sensor on that specific card.

**Comment by ludeeus** [comment]
This is actually the expected behavior.
Those buttons are mapped to the services `custom_updater.update_all` and `custom_updater.check_all`

The backend component does not care if its components or cards

**Comment by jmartensson** [comment]
thank you, then I know
