### ISSUE TITLE
After updating custom updater, new "has_update" row in table, is this supposed to happen?

### ISSUE THREAD

**Issue by rpitera** [custom-cards/tracker-card#18]
Not sure if this is working as intended or if I have configured something wrong.  Seems like an error though since it's 'has_update' and not "Has Update".  Can't find anything in the docs here or at the Custom Updater repo.

![clipboard01](https://user-images.githubusercontent.com/19910294/46224039-1e095580-c323-11e8-8060-65749f1d7a5d.png)

**Comment by ludeeus** [comment]
This issue are corrected in 2.7.3
https://github.com/custom-components/custom_updater/releases/tag/2.7.3

**Comment by ludeeus** [comment]
Ups...
Disregard the last comment, this is not resolved in the card

**Comment by ludeeus** [comment]
Fixed in version 0.1.5 of this card.
https://github.com/custom-cards/tracker-card/commit/7c2fdecff619b6dd1c7744062b3cd6a191cbe7de
