### ISSUE TITLE
Issue with check and update all for cards

### ISSUE THREAD

**Issue by sfnetwork** [custom-cards/tracker-card#24]
Pretty sure it's something not configured correctly but for my custom cards, the tracker card doesn't really report the right version and is not updating...

If I don't include "?v=0.1.5" at the end, the card doesn't show up at all but if I add it, "check" only show me whatever version is there... If I update all, it shows correct new version but "check" will switch it back...

![2018-10-17 08_50_16-home assistant](https://user-images.githubusercontent.com/5288374/47087381-d8390200-d1e9-11e8-8d94-59f9340723a4.png)

```
> resources:
>   - url: /local/tracker-card.js?v=0.1.5
>     type: js
>   - url: /local/custom-lovelace/button-card.jsv=0.0.2
>     type: module
>   - url: /local/custom-lovelace/upcoming-media-card/upcoming-media-card.js
>     type: js    
>   - url: /local/custom-lovelace/bignumber-card.js
>     type: js 
>   - url: /local/custom-lovelace/swipe-card/swipe-card.js?v=1.0
>     type: js 
```

**Comment by ludeeus** [comment]
What is your configuration?
And share the debug log for this :)
