### ISSUE TITLE
"Update all" removes the group of the ui-lovelace.yaml file

### ISSUE THREAD

**Issue by nicop4** [custom-cards/tracker-card#28]
Hi

When I hit "update all" button everything is updated as expected but the linux group of the `ui-lovelace.yaml` file is removed. It appears as `nogroup`.

I set write access rights to the homeassistant group for this file because the user I'm connected with does modifications to the file. So each time I update I have to re-set the group.
The rights are still there though.

<img width="654" alt="image" src="https://user-images.githubusercontent.com/10168765/51270161-85c3d900-19c4-11e9-9121-0578f0f7e7a0.png">

Is this possible for the tracker card to not change the group ?

**Comment by ludeeus** [comment]
The tracker card does not change anything ;)
it is using the `custom_updater` to change things, and that one is executing on behalf of the user running Home Assistant, so not sure how that can be changed.
Please open an issue here for this https://github.com/custom-components/custom_updater

**Comment by nicop4** [comment]
Yep, you're right sorry about that :)
I'll open the issue on the custom_updater github
