### ISSUE TITLE
please add individual update (opposed to update all)

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/tracker-card#31]
continuing from: https://github.com/custom-components/custom_updater/issues/71

reason: 
Now available updates for several custom cards only work for HA 86.+ and I am still and will be for a longer time on 84.3, I don't want to use, or can't use, update-all without rendering my system with a lot of issues and errors. Maybe even useless because of the continuous script errors.

solution:

 if it could have some safeguard or exclusion for updatable cards, that would make it so much more robust.

right now, I think we can go to the cards GitHub either by clicking the card name or the updatable red entry, with going to the same https. Couldn't you change the red entry , so clicking that would update that, and only that?

And maybe add a checkbox next to the cards to update when clicking update-all?

then all issues would be solved ;-)

thanks for considering

![schermafbeelding 2019-01-27 om 12 13 34](https://user-images.githubusercontent.com/33354141/51800263-ff618f80-222c-11e9-9700-8b724e8fe362.jpg)

**Comment by ludeeus** [comment]
1.1.0 of the tracker-card have support to update one at the time (by clicking the red version number)

You can also skip tracking completely for a card https://github.com/custom-components/custom_updater/wiki/Skip-tracking
