### ISSUE TITLE
Tracker-card not appearing in Custom Cards

### ISSUE THREAD

**Issue by cybergrimes** [custom-cards/tracker-card#33]
Hey there,

I'm having a hard time getting tracker-card to track itself. I've read through the closed issues and a bit on the forum but am unable to resolve. 

My config:
![config](https://user-images.githubusercontent.com/7375220/52178525-59b2a100-2795-11e9-9f0e-b4224adf1911.png)

The config in Lovelace, I've tried this as "v=0" too
![opera snapshot_2019-02-03_092411_192 168 0 201](https://user-images.githubusercontent.com/7375220/52178529-7e0e7d80-2795-11e9-9bab-14248e54f3a7.png)

I just manually updated to v0.2.0 and set the "v=0", did a reboot and lost all network access to system, I was able to access the partition and found this in the log:

> 2019-02-03 08:17:32 ERROR (MainThread) [frontend.js.latest.201901211] https://mynetworkaddress:port/local/tracker-card.js?v=0:1:1 Uncaught SyntaxError: Identifier 'TrackerCard' has already been declared

I renamed the tracker-card.js temporarily, got back into the front end and changed the v=0 to v=0.2.0 and everything is working fine now except I still can't see the tracker-card itself.

Here's what I get, check for updates/update all doesn't expose it either. Am I missing something obvious?
![opera snapshot_2019-02-03_092840_192 168 0 201](https://user-images.githubusercontent.com/7375220/52178594-363c2600-2796-11e9-9ea2-d10df73e42df.png)

thanks!

**Comment by ludeeus** [comment]
Are you using lovelace in storage mode?
<https://github.com/custom-components/custom_updater/wiki/Installation#note-about-tracking-cards-on-ha-version--0840>

**Comment by cybergrimes** [comment]
Yes I think I am, I was YAML until recently when it moved to the "lovelace" file in .storage
Sorry I had seen that in the wiki but didn't put it together. Thanks for the reply.
