### ISSUE TITLE
http://<myip:port>/local/tracker-card.js?v=0:7:1 Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by raoulteeuwen** [custom-cards/tracker-card#34]
So i keep getting thrown this error ... have looked around for a solution, also tried adding

frontend:
  javascript_version: latest

in configuration.yaml. I am using the raw version of the js. Any idea? I'm on a Rpi3 with HA 0.86.4.

**Comment by ludeeus** [comment]
If you get that error you did not get the raw file <https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins#uncaught-syntaxerror-unexpected-token->

**Comment by raoulteeuwen** [comment]
I believe that is normally the case, but just copied the raw version again, just to humor you, but still get reported that error. Maybe the error message is wrong (different component causing the error?), maybe user error, but i don't see what the solution is ... anyway, thank you for your response

**Comment by ludeeus** [comment]
You can try to add `?v=364278462492644289` at the end, in case you have the correct now, but the html variant earlier.
like:
```
url: /local/tracker-card.js?v=364278462492644289
```

**Comment by raoulteeuwen** [comment]
Thanks again. Tried. Log says: "ERROR (MainThread) [frontend.js.latest.201901211] http://<my ip & port>/local/tracker-card.js?v=0:7:1 Uncaught SyntaxError: Unexpected token <" ... it's o.k. to leave it, especially when i'm the only one (for now?)...

**Comment by ludeeus** [comment]
yeah, sorry I just tried the newest to and do not see the same issue 🤷‍♂️
