### ISSUE TITLE
Can someone elaborate on point 3 in installation instructions

### ISSUE THREAD

**Issue by imbaimbaimba** [custom-cards/tracker-card#36]
Hey everyone,
So, I don't understand point 3 in the installation instructions. Why do I need to add version to my existing cards, and what does that do? And how do I figure out what version to write in there?
Sorry, but I haven't been able to figure it out.

**Comment by ludeeus** [comment]
That is the local tag/version the component uses to determine the local version you have, initially you can set it to 1 for all, and the component will correct that number on first update
