### ISSUE TITLE
dynamic module importa is not implemented, firefox

### ISSUE THREAD

**Issue by aram535** [custom-cards/tracker-card#40]
I might be jumping the gun here as I noticed you had just uploaded this after refreshing my copy and seeing that something broke. 

I'm getting a "SyntaxError: dynamic module import is not implemented" at tracker-card.js:4:43. 
Doesn't seem to like that you're waiting for the tracker-file-editor module to be loaded.

I'm using FF 65.0.1 64x on Windows 10.

**Comment by ludeeus** [comment]
it will be in the next version of it.
until then add `?track=false` at the end of the URL for it in lovelace resources, so it will not track it until you can upgrade.

**Comment by aram535** [comment]
Changed.  Does it need a HA restart to catch?  A web refresh didn't work, getting a "Custom element doesn't exist: tracker-card."

**Comment by ludeeus** [comment]
Since you allready upgraded you need to downgrade the card first.
<https://raw.githubusercontent.com/custom-cards/tracker-card/58a6b3845a68afc820bd57be0d787729e0277a45/tracker-card.js>

**Comment by aram535** [comment]
Oh I see what I meant before sorry.  Yes I was futzing with my instance and downloaded the newer version before I saw that the version had changed.

**Comment by aram535** [comment]
That fixed it.  Thank you very much.

**Comment by kflinderman** [comment]
So I'm having this same problem, and I tried downloading that old card, but it hasn't changed anything. I'm on the same FF build on Win10 running 0.88.0. I don't know if it matters, but I also switched away from yaml lovelace, but I have `mode: storage` in my custom config.

I also just noticed my sensor.custom_card_tracker has:
```
 tracker-card: { "local": "1.1.1", "remote": "1.1.1", "has_update": false, "not_local": false, "repo": "https://github.com/custom-cards/tracker-card", "change_log": "https://github.com/custom-cards/tracker-card" }
```

even after running `custom_updater.check_all` with the old file

**Comment by ludeeus** [comment]
If you use the old card you need to add trackers to the configuration

**Comment by ludeeus** [comment]
FF Users can now use the newest version.

**Comment by aram535** [comment]
> I have `mode: storage` in my custom config

Not sure if storage works but the value in the docs is 'mode: yaml' 
https://www.home-assistant.io/lovelace/yaml-mode/

**Comment by ludeeus** [comment]
That is for the component @aram535 
https://github.com/custom-components/custom_updater/wiki/Installation#configuration-option-mode
