### ISSUE TITLE
v1.0 is ?track=true needed?

### ISSUE THREAD

**Issue by adrianmihalko** [custom-cards/tracker-card#41]
The doc is little bit confusing. 

Custom_updater release doc:

old example:

```
resources: 
  - url: /local/tracker-card.js?v=0.3.0
    type: js
new example:

resources: 
  - url: /customcards/tracker-card.js
    type: js
```

...and in tracker card doc:

`/customcards/tracker-card.js?track=true`

What is the correct way to use?

**Comment by ludeeus** [comment]
If you downloaded it manually (or upgraded) then no.

`?track=true` is a part of a new funtrion for automatically downloading the card but if you use that the "url" needs to be exactly `/customcards/github/custom-cards/tracker-card.js?track=true`
