### ISSUE TITLE
With upgrade to 1.0.0 and switch from js to module tracker card no longer works in Firefox

### ISSUE THREAD

**Issue by olbjan** [custom-cards/tracker-card#43]
After the update to v1.0 the tracker card no longer shows in Firefox (65.0.1 64-bit) or Microsoft Edge (1809). The error displayed is

Custom element doesn't exist: tracker-card.

{
  "type": "custom:tracker-card"
}

In Chrome and iOS Safari it's working as expected.

**Comment by ludeeus** [comment]
That is expected and the same as #40 

Until the browser supports it, downgrade the card and `track=false` to it.
https://github.com/custom-components/custom_updater/wiki/Skip-tracking

**Comment by ludeeus** [comment]
FF Users can now use the newest version.

**Comment by zbuh** [comment]
Updated, but still gives the same error in FF

**Comment by ludeeus** [comment]
Clear your cache, the newest version does not import other modules.

**Comment by zbuh** [comment]
I've done that.
Updated to latest version with chrome.
But with FF: 
```
https://xxxxxxxxxx:8123/customcards/tracker-card.js?track=true:215:71 SyntaxError: dynamic module import is not implemented
08:45 components/system_log/__init__.py (ERROR) - message first occured at 08:20 and shows up 7 times
```

**Comment by ludeeus** [comment]
Yup...
There was one more import, I have removed that now and 1.2.1 should work.

**Comment by zbuh** [comment]
fixed! ;)
