### ISSUE TITLE
Uncaught SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by steeriks** [custom-cards/tracker-card#45]
Problem with the tracker-card. I hade 1.20 then I updated the card. Then bang… _“ERROR (MainThread) [frontend.js.latest.201902200] https://192.168.10.90:8123/customcards/tracker-card.js:231:1 Uncaught SyntaxError: Unexpected token export”

Running hassio 0.88 on Ubuntu 18.04 and Lovelace in yaml mode.

**Comment by ludeeus** [comment]
That is stupid...
Upgrade to 1.2.2

**Comment by steeriks** [comment]
Thanks, upgraded. Looks fine :-)
