### ISSUE TITLE
Tracker Card no longer working after update to HA 0.88.0

### ISSUE THREAD

**Issue by Obicom** [custom-cards/tracker-card#46]
HA Version:
Hassio 0.88.0

I did the HA update to version 0.88.0 and prepared the tracker card as described. No if have a new folder under www->github->custom-cards->tracker-card.js
In my lovelace UI (storage) file I have:
![image](https://user-images.githubusercontent.com/25134482/53175525-6be16b80-35ec-11e9-8ccf-8c0ea06dd80e.png)

custom upadter is also working ... and under .storage/custom_updater cards is:
![image](https://user-images.githubusercontent.com/25134482/53175635-ab0fbc80-35ec-11e9-96f9-40648875df21.png)

but if I put in thr lovelace RAW file the entry: "type: custom:tracker-card" I get this error
![image](https://user-images.githubusercontent.com/25134482/53175798-09d53600-35ed-11e9-80a6-628c395f32ca.png)

Any idea why and how I can fix it?

**Comment by ludeeus** [comment]
Clear the cache of your browser, if that does not help restart Home Assistant

**Comment by Obicom** [comment]
Thank you very much .. sometimes it could be so easy ... ;)
