### ISSUE TITLE
Uncaught TypeError: Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by adrianmihalko** [custom-cards/tracker-card#48]
Custom updater & tracker card worked for me fine until I upgraded to 0.88. After upgrading I don't see the tracker card. 

Custom updater works:

<img width="126" alt="screenshot 2019-02-22 at 19 59 05" src="https://user-images.githubusercontent.com/733361/53265479-a88d8f80-36de-11e9-9089-338069f2fc78.png">

Tracker card errors:

<img width="1280" alt="screenshot 2019-02-22 at 20 01 42" src="https://user-images.githubusercontent.com/733361/53265491-af1c0700-36de-11e9-8979-dd3b1d2b080a.png">

1. cache cleared, HA restarted.

Log:

```
2019-02-22 20:09:14 ERROR (MainThread) [frontend.js.latest.201902200] http://192.168.1.155:8123/customcards/github/custom-cards/tracker-card.js?track=true:201:54 Uncaught TypeError: Cannot read property 'addEventListener' of null
2019-02-22 20:09:14 ERROR (MainThread) [frontend.js.latest.201902200] http://192.168.1.155:8123/customcards/github/custom-cards/tracker-card.js?track=true:201:54 Uncaught TypeError: Cannot read property 'addEventListener' of null
2019-02-22 20:09:58 ERROR (MainThread) [frontend.js.latest.201902200] http://192.168.1.155:8123/customcards/github/custom-cards/tracker-card.js?track=true:201:54 Uncaught TypeError: Cannot read property 'addEventListener' of null
madrian@ubuntudev:/usr/share/hassio/homeassistant$ curl "http://192.168.1.155:8123/customcards/github/custom-cards/tracker-card.js?track=true"
class TrackerCard extends HTMLElement
```

Config:

```
resources:
  - type: module
    url: /customcards/github/custom-cards/tracker-card.js?track=true
```

```
  - badges: []
    cards:
      - type: 'custom:tracker-card'
    icon: 'mdi:home-assistant'
    title: System
```

**Comment by joelstahre** [comment]
Same here, but i have never used it before, tried to set it up today. i get:

`2019-02-22 21:58:38 ERROR (MainThread) [custom_components.custom_updater] Tried to serve up '/config/www/github/custom-cards/tracker-card.js' but it does not exist`

**Comment by ludeeus** [comment]
@joelstahre run the service as stated in the readme

**Comment by joelstahre** [comment]
<img width="522" alt="screenshot 2019-02-22 at 22 46 24" src="https://user-images.githubusercontent.com/2317917/53273263-d7623080-36f3-11e9-8f1c-efd2b2e62d80.png">


I have done that multiple times.

**Comment by ludeeus** [comment]
if that is the case open an issue where https://github.com/custom-components/custom_updater/issues

**Comment by ludeeus** [comment]
Can you try a different browser @adrianmihalko ?

**Comment by simbesh** [comment]
I also am setting up tracker-card/ custom_updater for the first time on hassio 0.88.1. Getting the same error as @joelstahre

**Comment by adrianmihalko** [comment]
@ludeeus 

I tried with Safar/Chrome/Firefox.

<img width="1280" alt="screenshot 2019-02-23 at 11 28 14" src="https://user-images.githubusercontent.com/733361/53285196-2fce1800-375e-11e9-8810-379758bd3010.png">

**Comment by ludeeus** [comment]
Can you try the latest version(1.2.4)?

**Comment by adrianmihalko** [comment]
It works now.

```@ubuntudev:/usr/share/hassio/homeassistant/www/github/custom-cards$ ls -lah
total 20K
drwxr-xr-x 2 root root 4.0K Feb 22 20:01 .
drwxr-xr-x 3 root root 4.0K Feb 22 20:01 ..
-rw-r--r-- 1 root root 9.2K Feb 22 20:01 tracker-card.js
@ubuntudev:/usr/share/hassio/homeassistant/www/github/custom-cards$ sudo rm tracker-card.js
@ubuntudev:/usr/share/hassio/homeassistant/www/github/custom-cards$ ls -lah
total 20K
drwxr-xr-x 2 root root 4.0K Feb 23 13:58 .
drwxr-xr-x 3 root root 4.0K Feb 22 20:01 ..
-rw-r--r-- 1 root root 9.6K Feb 23 13:58 tracker-card.js
```

Deleted browser cache and it shows up. 👍

Thank you.
