### ISSUE TITLE
Font odd when updates available and on Mobile (iOS)

### ISSUE THREAD

**Issue by DavidFW1960** [custom-cards/tracker-card#49]
Why does the available column go to a different font when updates are available or on a mobile device?
![img_0065](https://user-images.githubusercontent.com/36390762/53317683-b3cffd80-3920-11e9-928a-2d52a56f32b6.jpg)
It always looks like this on mobile and when there are available updates on my PC (Win10 chrome) it does it in the right hand column as well

**Comment by ludeeus** [comment]
Corrected in newest version

**Comment by DavidFW1960** [comment]
Nice. Thanks.
