### ISSUE TITLE
Tracker-Card look and feel not updated 

### ISSUE THREAD

**Issue by aptonline** [custom-cards/tracker-card#50]
I’m running the latest tracker-card (1.2.5) but not seeing the new look and feel of the card. As seen here: https://github.com/custom-cards/tracker-card I removed ``mode:storage`` as 0.88.1 complained about the key.

I’ve cleared the cache (safari iOS) and the issue has not resolved. Same on iOS home assistant app.

**Comment by iantrich** [comment]
Try a private session. If that doesn't work, try redownloading

**Comment by aptonline** [comment]
Tried both, same to issue. I’m looking for the icon change in the card header which I’m assuming will tell me it’s installed.

**Comment by ludeeus** [comment]
Icon change? That icon is the same that it has been since the initial version

**Comment by aptonline** [comment]
![7a86e0b3-b62e-4f93-b1fe-918f641087c5](https://user-images.githubusercontent.com/190136/53344086-b70bbf00-3909-11e9-82ce-6a0fa33e6b73.png)

Mine is different ( 📣 )

**Comment by aptonline** [comment]
Is this a Unicode difference between devices? If so im a muppet.

**Comment by ludeeus** [comment]
Most likely, I do not see a difference 
![image](https://user-images.githubusercontent.com/15093472/53346902-43bd7980-3918-11e9-9b04-6ccf00ddcabe.png)

**Comment by aptonline** [comment]
I ‘assumed’ newer card hence the issue. Closing now as happy.
