### ISSUE TITLE
custom_updater shows update but is on current version (4.2.16)

### ISSUE THREAD

**Issue by Obicom** [custom-cards/tracker-card#52]
Today I saw a new update for custom_updater and pressed the update all button. As I can see the new file was downloaded but tracker card shows it would be still old version 4.2.15. Refresh was done (F5).

![image](https://user-images.githubusercontent.com/25134482/53645328-ed627a80-3c38-11e9-82dd-4d668ef7e6e5.png)

![image](https://user-images.githubusercontent.com/25134482/53645379-066b2b80-3c39-11e9-9f6a-85dc92b294f8.png)

**Comment by ludeeus** [comment]
That is a new feature.
You are not using the updated version until you restart HA and it loads the new file.

**Comment by ludeeus** [comment]
There is a FR here https://github.com/custom-components/custom_updater/issues/116
I will not implement it, but anyone else feel free to create a PR for it.
