### ISSUE TITLE
Option to update individually removed?

### ISSUE THREAD

**Issue by PlayedIn** [custom-cards/tracker-card#54]
Has the option to update individual cards been removed?  I use to be able to click the red version numbers showing up on the card to update individual cards.   Now it doesn't even appear to be clickable.  If I click it any way, of course nothing happens.    

I'm on the latest tracker card 1.2.6.  HA 91.2.  Update all works just fine.

This is the added option I'm referring to:
https://github.com/custom-cards/tracker-card/issues/31

**Comment by ludeeus** [comment]
Unfortunately yes, it caused more issues then it solved.
I will not try that again, but anyone else are welcome to try it and make a PR to include it when ready 🎉
