### ISSUE TITLE
Abandoned Project?

### ISSUE THREAD

**Issue by Talk2Giuseppe** [custom-cards/tracker-card#61]
I'm having trouble getting this to work in the most current version of HA.  In the installation instructions of this project, it states that "Custom Updater" must be installed first.  Yet, the project, "Custom Updater" is deprecated.  I took a shot at installing the abandoned Custom Updater manually, then proceeded with the installation of this project.  Yet attempting to call the custom_updater.check_all yields no results.

Does anyone have this project currently working, and if so, how did you get it up and running?

**Comment by ludeeus** [comment]
Definitely abandoned.
Was replaced with https://hacs.xyz/
