### ISSUE TITLE
n.setConfig is not a function

### ISSUE THREAD

**Issue by K-RAD** [custom-cards/tracker-card#8]
I've just installed HAAS (on Win) and I'm tinkering a bit with it. Installing the tracker-card, I get "n.setConfig is not a function"

![image](https://user-images.githubusercontent.com/3822874/43945025-3e134c28-9c81-11e8-8e77-a6db8bab61cb.png)

**Comment by ciotlosm** [comment]
You're running javascript es5 probably. Read https://github.com/ciotlosm/custom-lovelace#faq and see if you find a fix

**Comment by K-RAD** [comment]
it was just a mistake in the config, frontend was commented out for some reason
